---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webstores.marketplace.com
spec:
  group: marketplace.com
  names:
    kind: WebStore
    plural: webstores
    singular: webstore
  preserveUnknownFields: false
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            employees:
              type: integer
            product:
              type: string
          required:
          - product
          - employees
          type: object
      type: object
  versions:
  - name: v1
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
