# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  enableMultiRepo: true
  patches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: admission-webhook
      namespace: config-management-system
    spec:
      template:
        spec:
          containers:
          - name: admission-webhook
            resources:
              limits:
                memory: "200Mi"
