# root-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://github.com/haiyanmeng/csmr-sample
    dir: "root-hier"
    auth: none
  sourceFormat: hierarchy
