# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  override:
    resources:
    - containerName: "reconciler"
      cpuLimit: "333m"
      memoryLimit: "333Mi"
  git:
    repo: https://github.com/haiyanmeng/csmr-sample
    dir: bookstore
    auth: none
  sourceFormat: unstructured
