# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    noSSLVerify: true
    repo: https://github.com/haiyanmeng/kubevirt
    branch: main
    auth: none
  sourceFormat: unstructured
