# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://source.developers.google.com/p/haiyanmeng-gke-322517/r/csmr-sample
    branch: master
    dir: bookstore
    auth: gcenode
  sourceFormat: unstructured
  #sourceFormat: hierarchy
