# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: git@github.com:haiyanmeng/csmr-sample.git
    dir: "root-hier"
    auth: ssh
    secretRef:
      name: git-creds
  sourceFormat: hierarchy
