apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-1
  name: atp-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-1
  name: atp-ops-rb
  namespace: atp-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-console-reader
subjects:
  - kind: Group
    name: IT-APP-BDP-EDGE-GBL-ATP-OPS
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-1
  name: atp-dev-rb
  namespace: atp-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-dev-role
subjects:
  - kind: Group
    name: IT-APP-BDP-EDGE-GBL-ATP-DEV
  - kind: Group
    name: IT-APP-BDP-EDGE-GBL-ATP-ADM
  - kind: ServiceAccount
    name: atp-service-account
    namespace: tenant-resources
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-1
  name: atp-quota
  namespace: atp-prd
spec:
  hard:
    limits.cpu: "129"
    limits.ephemeral-storage: 20Gi
    limits.memory: 276Gi
    requests.cpu: "109"
    requests.memory: 230Gi
    requests.storage: 20Gi
