apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-a
  namespace: bookstore
  annotations:
    #configmanagement.gke.io/managed: disabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-b
  namespace: bookstore
  annotations:
    config.kubernetes.io/depends-on: /namespaces/bookstore/ConfigMap/cm-a
