apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: bookstore
  annotations:
    ann-kubectl: dwd
    owner: "aiyan"
    hello: "true"
    #configmanagement.gke.io/managed: disabled
    #client.lifecycle.config.k8s.io/mutation: ignore
  #annotations:
  #configmanagement.gke.io/managed: disabled
spec:
  replicas: 1
  minReadySeconds: 9
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
