apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    configmanagement.gke.io/managed: disabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: default
  annotations:
    configmanagement.gke.io/managed: disabled
