apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  annotations:
    configmanagement.gke.io/managed: disabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: test-ns
  annotations:
    configmanagement.gke.io/managed: disabled
