apiVersion: example.com/v1
kind: CronTab
metadata:
  name: ct1
  namespace: bookstore
  annotations:
    weather: "sunny"
    #configsync.gke.io/declared-version: "v1beta1"
host: "11helo"
port: "212"
