apiVersion: example.com/v1beta1
kind: CronTab
metadata:
  name: ct1
  namespace: bookstore
  annotations:
    weather: "sunny"
host: "local"
port: "12"
name: "lolo"
gender: "m"
aa: "ddd"
bb: "d23"
cc: "23"
