---
apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: bookstore
spec:
  git:
    auth: ssh
    branch: master
    dir: bookstore
    repo: https://github.com/haiyanmeng/csmr-sample
    secretRef:
      name: git-creds
  sourceFormat: unstructured
