---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atp-ops-rb
  namespace: atp-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-console-reader
subjects:
- kind: Group
  name: IT-APP-BDP-EDGE-GBL-ATP-OPS
